name: Unzip File

on:
  push:
    paths:
      - '.github/workflows/卡方-料方.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Unzip file
        run: unzip .github/workflows/卡方-料方.zip -d ./unzipped_content
